x-templates:
  nestjs-microservice-config: &nestjs-microservice-config
    port: 3000
    probe:
      path: /graphql?query=%7B__typename%7D
      port: 3000
  nestjs-microservice-env: &nest-microservice-env
    HOST: 0.0.0.0
    PORT: "3000"
    RABBIT_RMQ_URL: amqp://admin:admin@rabbit:5672
    RABBIT_HTTP_URL: http://admin:admin@rabbit:15672

microservices:
  auth:
    <<: *nestjs-microservice-config
    image: ghcr.io/kishieel/relegatio-auth:1.0.2
    development:
      enabled: true
      source: /volumes/microservices/auth
    hooks:
      prisma.sh:
        type: post-install,post-upgrade
        weight: 5
        source: |
          #!/usr/bin/env sh
          yarn prisma migrate deploy
          yarn prisma generate
    env:
      <<: *nest-microservice-env
      DATABASE_URL: mysql://root:root@mysql:3306/auth
      JWT_SECRET: secret
      ACCESS_TOKEN_EXPIRES_IN: 30d
      REFRESH_TOKEN_EXPIRES_IN: 30d

  gateway:
    <<: *nestjs-microservice-config
    image: ghcr.io/kishieel/relegatio-gateway:1.0.3
    development:
      enabled: true
      source: /volumes/microservices/gateway
    env:
      <<: *nest-microservice-env
      POSTS_GRAPHQL_URL: http://posts:3000/graphql
      AUTH_GRAPHQL_URL: http://auth:3000/graphql
    ingresses:
      gateway:
        enabled: true
        name: gateway
        hostname: api.relegatio.localhost
        path: /graphql
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /graphql

  notifications:
    <<: *nestjs-microservice-config
    image: ghcr.io/kishieel/relegatio-notifications:1.0.2
    development:
      enabled: true
      source: /volumes/microservices/notifications
    probe:
      path: /health
      port: 3000
    env:
      <<: *nest-microservice-env
      DATABASE_URL:
        value: notifications

  posts:
    <<: *nestjs-microservice-config
    image: ghcr.io/kishieel/relegatio-posts:1.0.3
    development:
      enabled: true
      source: /volumes/microservices/posts
    env:
      <<: *nest-microservice-env
      DATABASE_URL: http://admin:admin@couchdb-svc-couchdb:5984

  frontend:
    image: ghcr.io/kishieel/relegatio-frontend:1.0.1
    port: 3000
    development:
      enabled: true
      source: /volumes/microservices/frontend
    probe:
      path: /
      port: 3000
    env:
      GRAPHQL_URL: http://gateway:3000/graphql
      HOST: 0.0.0.0
      PORT: "3000"
    ingresses:
      frontend:
        enabled: true
        name: frontend
        hostname: relegatio.localhost
        path: /
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /

mysql:
  fullnameOverride: mysql
  auth:
    username: admin
    password: admin
    rootPassword: root
    defaultAuthenticationPlugin: caching_sha2_password
  initdbScripts:
    create-database.sql: |
      CREATE DATABASE IF NOT EXISTS auth;
      GRANT ALL PRIVILEGES ON auth.* TO 'admin'@'%';
  primary:
    persistence:
      enabled: true

redis:
  fullnameOverride: redis
  persistence:
    enabled: true

rabbitmq:
  fullnameOverride: rabbit
  auth:
    username: admin
    password: admin
  persistence:
    enabled: true
  ingress:
    enabled: true
    hostname: rabbit.relegatio.localhost
    ingressClassName: nginx

couchdb:
  fullnameOverride: couchdb
  adminUsername: admin
  adminPassword: admin
  cookieAuthSecret: cookie-auth-secret
  clusterSize: 3
  enableSearch: true
  persistentVolume:
    enabled: true
  erlangFlags:
    setcookie: make-something-up
  autoSetup:
    enabled: true
    defaultDatabases:
      - _global_changes
      - _replicator
      - _users
  couchdbConfig:
    couchdb:
      uuid: 1298f2bb208f47a69f31a7d6afdd05f5
  ingress:
    enabled: true
    hosts:
      - couchdb.relegatio.localhost
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "couchdb-session"
      nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"

mailpit:
  fullnameOverride: mailpit
  ingress:
    enabled: true
    hostname: mailpit.relegatio.localhost
    ingressClassName: nginx

imagePullSecrets:
  - name: ghcr-secret

localUid: 1000
localGid: 1000
