x-templates:
  ts-microservice-config: &ts-microservice-config
    port: 3000
  ts-microservice-env: &ts-microservice-env
    HOST:
      value: 0.0.0.0
    PORT:
      value: 3000

microservices:
  auth:
    <<: *ts-microservice-config
    image: ghcr.io/kishieel/relegatio-auth:1.0.0
    development:
      enabled: true
      source: /volumes/microservices/auth
    env:
      <<: *ts-microservice-env
      DATABASE_URL:
        value: microservices
      RABBIT_RMQ_URL:
        value: amqp://guest:guest@rabbit:5672
      RABBIT_HTTP_URL:
        value: http://rabbit:15672
      JWT_SECRET:
        value: secret # @todo: change this to a secret or environment variable

  gateway:
    <<: *ts-microservice-config
    image: ghcr.io/kishieel/relegatio-gateway:1.0.2
    development:
      enabled: true
      source: /volumes/microservices/gateway
    env:
      <<: *ts-microservice-env

  notifications:
    <<: *ts-microservice-config
    image: ghcr.io/kishieel/relegatio-notifications:1.0.1
    development:
      enabled: true
      source: /volumes/microservices/notifications
    env:
      <<: *ts-microservice-env
      DATABASE_URL:
        value: notifications

  posts:
    <<: *ts-microservice-config
    image: ghcr.io/kishieel/relegatio-posts:1.0.2
    development:
      enabled: true
      source: /volumes/microservices/posts
    env:
      <<: *ts-microservice-env
      DATABASE_URL:
        value: posts

mysql:
  fullnameOverride: mysql
  primary:
    persistence:
        enabled: true

redis:
  fullnameOverride: redis
  persistence:
    enabled: true

rabbitmq:
  fullnameOverride: rabbit
  auth:
    username: admin
    password: admin
  persistence:
    enabled: true
  ingress:
    enabled: true
    hostname: rabbit.relegatio.localhost
    ingressClassName: nginx

couchdb:
  fullnameOverride: couchdb
  adminUsername: admin
  adminPassword: admin
  clusterSize: 2
  enableSearch: true
  persistentVolume:
    enabled: true
  autoSetup:
    enabled: true
    defaultDatabases:
      - _global_changes
      - _replicator
      - _users
  couchdbConfig:
    couchdb:
      uuid: 1298f2bb208f47a69f31a7d6afdd05f5
  ingress:
    enabled: true
    hosts:
      - couchdb.relegatio.localhost
    className: nginx

mailpit:
  fullnameOverride: mailpit
  ingress:
    enabled: true
    hostname: mailpit.relegatio.localhost
    ingressClassName: nginx

ingress:
  gateway:
    enabled: true
    serviceName: gateway
    servicePort: 3000
    hostname: api.relegatio.localhost
    path: /graphql
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /graphql

imagePullSecrets:
  - name: ghcr-secret

localUid: 1000
localGid: 1000
