{{- range $ingressName, $ingressConfig := .Values.ingress }}
{{- if $ingressConfig.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  annotations:
    {{- toYaml $ingressConfig.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $ingressConfig.hostname }}
      http:
        paths:
          - path: {{ $ingressConfig.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ingressConfig.serviceName }}
                port:
                  number: {{ $ingressConfig.servicePort }}
---
{{- end }}
{{- end }}
