{{- range $serviceName, $serviceConfig := .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    name: {{ $serviceName }}
  ports:
    - port: 3000
      targetPort: 3000
---
{{- end }}
