{{- range $serviceName, $serviceConfig := .Values.microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    name: {{ $serviceName }}
spec:
  selector:
    matchLabels:
      name: {{ $serviceName }}
  template:
    metadata:
      labels:
        name: {{ $serviceName }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      {{- if ($serviceConfig.development).enabled }}
      securityContext:
        runAsUser: {{ $.Values.localUid }}
        runAsGroup: {{ $.Values.localGid }}
        fsGroup: {{ $.Values.localGid }}
      {{- end }}
      {{/* initContainers: only for gateway to wait for another service */}}
      containers:
        - name: {{ $serviceName }}
          image: {{ $serviceConfig.image }}
          ports:
            - containerPort: {{ $serviceConfig.port }}
          imagePullPolicy: IfNotPresent
          env:
          {{- range $envName, $envValue := $serviceConfig.env }}
            - name: {{ $envName }}
              value: "{{ $envValue }}"
          {{- end }}
          resources:
            limits:
              cpu: 2000m {{/* @todo: adjust these values for production and development */}}
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          {{- if ($serviceConfig.development).enabled }}
          volumeMounts:
            - mountPath: /app
              name: {{ $serviceName }}-code
          {{- end }}
          {{- if $serviceConfig.probe }}
          livenessProbe:
            httpGet:
              path: {{ default "/" $serviceConfig.probe.path  }}
              port: {{ default 3000 $serviceConfig.probe.port }}
              httpHeaders:
                - name: apollo-require-preflight
                  value: "true"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ default "/" $serviceConfig.probe.path  }}
              port: {{ default 3000 $serviceConfig.probe.port }}
              httpHeaders:
                - name: apollo-require-preflight
                  value: "true"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          {{- end }}
      {{- if ($serviceConfig.development).enabled }}
      volumes:
        - name: {{ $serviceName }}-code
          hostPath:
            path: {{ ($serviceConfig.development).source }}
            type: Directory
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    name: {{ $serviceName }}
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $serviceName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $serviceName }}
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
{{- range $ingressName, $ingressConfig := $serviceConfig.ingresses }}
{{- if $ingressConfig.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  annotations:
    {{- toYaml $ingressConfig.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $ingressConfig.hostname }}
      http:
        paths:
          - path: {{ $ingressConfig.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $serviceConfig.port }}
---
{{- end }}
{{- end }}
{{- if $serviceConfig.hooks }}
{{- range $hookName, $hookConfig := $serviceConfig.hooks }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-{{ $hookName | replace "." "-" }}-configmap
data:
  {{ $hookName }}:
    {{- toYaml $hookConfig.source | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $serviceName }}-{{ $hookName | replace "." "-" }}
  annotations:
    "helm.sh/hook": {{ $hookConfig.type }}
    "helm.sh/hook-weight": {{ $hookConfig.weight | quote }}
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ $serviceName }}-{{ $hookName | replace "." "-" }}
    spec:
      restartPolicy: Never
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      {{- if ($serviceConfig.development).enabled }}
      securityContext:
        runAsUser: {{ $.Values.localUid }}
        runAsGroup: {{ $.Values.localGid }}
        fsGroup: {{ $.Values.localGid }}
      {{- end }}
      containers:
        - name: {{ $serviceName }}-{{ $hookName | replace "." "-" }}
          image: {{ $serviceConfig.image }}
          imagePullPolicy: IfNotPresent
          env:
          {{- range $envName, $envValue := $serviceConfig.env }}
            - name: {{ $envName }}
              value: "{{ $envValue }}"
          {{- end }}
          command:
            - /bin/{{ $hookName }}
          volumeMounts:
            {{- if ($serviceConfig.development).enabled }}
            - mountPath: /app
              name: {{ $serviceName }}-code
            {{- end }}
            - name: {{ $serviceName }}-{{ $hookName | replace "." "-" }}-configmap
              mountPath: /bin/{{ $hookName }}
              subPath: {{ $hookName }}
              readOnly: true
      volumes:
        {{- if ($serviceConfig.development).enabled }}
        - name: {{ $serviceName }}-code
          hostPath:
            path: {{ ($serviceConfig.development).source }}
            type: Directory
        {{- end }}
        - name: {{ $serviceName }}-{{ $hookName | replace "." "-" }}-configmap
          configMap:
            name: {{ $serviceName }}-{{ $hookName | replace "." "-" }}-configmap
            defaultMode: 0777 # @todo: somehow I don't like this, check if I can set owner of this file to container user
  backoffLimit: 1
  ttlSecondsAfterFinished: 30
  activeDeadlineSeconds: 30
---
{{- end }}
{{- end }}
{{- end }}
